import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { FaCheck, FaExternalLinkAlt, FaGithub, FaTimes } from "react-icons/fa";
import { projectsData } from "../data/portfolioData";

function ProjectModal({ project, onClose }) {
  useEffect(() => {
    const handleKeydown = (event) => event.key === "Escape" && onClose();
    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, [onClose]);

  return <motion.div role="dialog" aria-modal="true" aria-labelledby="modal-title" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose} className="fixed inset-0 z-[95] grid place-items-center bg-slate-950/80 p-4 backdrop-blur-md"><motion.div initial={{ opacity: 0, y: 24, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 16 }} onMouseDown={(event) => event.stopPropagation()} className="relative max-h-[88vh] w-full max-w-3xl overflow-y-auto rounded-[1.75rem] border border-white/15 bg-slate-900/95 p-6 shadow-2xl shadow-cyan-500/10 sm:p-8"><button onClick={onClose} aria-label="Close project details" className="absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full border border-white/10 text-slate-300 hover:border-cyan-300 hover:text-cyan-300"><FaTimes /></button><p className="eyebrow">{project.category} project</p><h2 id="modal-title" className="pr-10 text-3xl font-black text-white">{project.title}</h2><p className="mt-5 max-w-2xl leading-7 text-slate-300">{project.details.summary}</p><div className="mt-8 grid gap-7 md:grid-cols-2"><div><h3 className="font-bold text-white">Core features</h3><ul className="mt-3 space-y-3">{project.details.features.map((feature) => <li key={feature} className="flex gap-3 text-sm leading-6 text-slate-400"><FaCheck className="mt-1 shrink-0 text-cyan-300" />{feature}</li>)}</ul></div><div><h3 className="font-bold text-white">Challenge solved</h3><p className="mt-3 text-sm leading-7 text-slate-400">{project.details.challenge}</p><h3 className="mt-6 font-bold text-white">Technology stack</h3><div className="mt-3 flex flex-wrap gap-2">{project.details.stack.map((tech) => <span key={tech} className="rounded-lg bg-cyan-300/10 px-3 py-1.5 text-xs font-semibold text-cyan-100">{tech}</span>)}</div></div></div></motion.div></motion.div>;
}

function Projects() {
  const [filter, setFilter] = useState("All");
  const [selected, setSelected] = useState(null);
  const filters = ["All", ...new Set(projectsData.map((project) => project.category))];
  const visibleProjects = filter === "All" ? projectsData : projectsData.filter((project) => project.category === filter);
  return <><section id="projects" className="section-shell px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Selected work</p><h2 className="section-title">Projects that solve real problems.</h2></div><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${filter === item ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300 hover:border-cyan-300"}`}>{item}</button>)}</div></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{visibleProjects.map((project, index) => <motion.article layout key={project.title} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} whileHover={{ y: -9, rotateX: 2, rotateY: -2 }} style={{ transformPerspective: 900 }} className="interactive-card group overflow-hidden rounded-[1.5rem] border border-white/10 bg-slate-800/50 shadow-xl shadow-slate-950/20"><button onClick={() => setSelected(project)} aria-label={`View ${project.title} details`} className="block w-full text-left"><div className="relative overflow-hidden"><img src={project.image} alt={`${project.title} preview`} loading="lazy" className="h-48 w-full object-cover opacity-75 transition duration-500 group-hover:scale-110 group-hover:opacity-100" /><div className="absolute inset-0 bg-gradient-to-t from-slate-900 to-transparent" /></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">{project.category} project</p><h3 className="mt-3 text-xl font-bold text-white">{project.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-md bg-blue-500/10 px-2.5 py-1 text-xs text-blue-200">{tag}</span>)}</div></div></button><div className="flex gap-3 px-6 pb-6"><a href={project.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs font-bold text-white transition hover:border-cyan-300 hover:text-cyan-300"><FaGithub />Code</a><button onClick={() => setSelected(project)} className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-xs font-bold text-slate-950 transition hover:bg-cyan-200">Details <FaExternalLinkAlt /></button></div></motion.article>)}</div></div></section><AnimatePresence>{selected && <ProjectModal project={selected} onClose={() => setSelected(null)} />}</AnimatePresence></>;
}
export default Projects;
